<a href="https://colab.research.google.com/github/nattapon44/time-table-project/blob/main/model33.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATA**

A set of time period T

In [11]:
T = { 1: {"Day": (1, "Monday"),
		      "Hour": (1, "8 am")},
   	  2: {"Day": (1, "Monday"),
		      "Hour": (2, "8:30 am")},
	    3: {"Day": (1, "Monday"),
	     	  "Hour": (3, "9 am")},
	    4: {"Day": (1, "Monday"),
		      "Hour": (4, "9:30 am")},
   	  5: {"Day": (1, "Monday"),
		      "Hour": (5, "10 am")},
	    6: {"Day": (1, "Monday"),
	     	  "Hour": (6, "10:30 am")},
      7: {"Day": (1, "Monday"),
	     	  "Hour": (7, "11 am")},
      8: {"Day": (1, "Monday"),
		      "Hour": (8, "11:30 am")},
   	  9: {"Day": (1, "Monday"),
		      "Hour": (9, "1 pm")},
	    10: {"Day": (1, "Monday"),
	     	  "Hour": (10, "1:30 pm")},
	    11: {"Day": (1, "Monday"),
		      "Hour": (11, "2 pm")},
   	  12: {"Day": (1, "Monday"),
		      "Hour": (12, "2:30 pm")},
	    13: {"Day": (1, "Monday"),
	     	  "Hour": (13, "3 pm")},
      14: {"Day": (1, "Monday"),
	     	  "Hour": (14, "3:30 pm")},
      15: {"Day": (1, "Monday"),
		      "Hour": (15, "4 pm")},
   	  16: {"Day": (1, "Monday"),
		      "Hour": (16, "4:30 pm")},
	    17: {"Day": (1, "Monday"),
	     	  "Hour": (17, "5 pm")},
	    18: {"Day": (1, "Monday"),
		      "Hour": (18, "5:30 pm")},
      19: {"Day": (2, "Tuesday"),
		      "Hour": (1, "8 am")},
   	  20: {"Day": (2, "Tuesday"),
		      "Hour": (2, "8:30 am")},
	    21: {"Day": (2, "Tuesday"),
	     	  "Hour": (3, "9 am")},
	    22: {"Day": (2, "Tuesday"),
		      "Hour": (4, "9:30 am")},
   	  23: {"Day": (2, "Tuesday"),
		      "Hour": (5, "10 am")},
	    24: {"Day": (2, "Tuesday"),
	     	  "Hour": (6, "10:30 am")},
      25: {"Day": (2, "Tuesday"),
	     	  "Hour": (7, "11 am")},
      26: {"Day": (2, "Tuesday"),
		      "Hour": (8, "11:30 am")},
   	  27: {"Day": (2, "Tuesday"),
		      "Hour": (9, "1 pm")},
	    28: {"Day": (2, "Tuesday"),
	     	  "Hour": (10, "1:30 pm")},
	    29: {"Day": (2, "Tuesday"),
		      "Hour": (11, "2 pm")},
   	  30: {"Day": (2, "Tuesday"),
		      "Hour": (12, "2:30 pm")},
	    31: {"Day": (2, "Tuesday"),
	     	  "Hour": (13, "3 pm")},
      32: {"Day": (2, "Tuesday"),
	     	  "Hour": (14, "3:30 pm")},
      33: {"Day": (2, "Tuesday"),
		      "Hour": (15, "4 pm")},
   	  34: {"Day": (2, "Tuesday"),
		      "Hour": (16, "4:30 pm")},
	    35: {"Day": (2, "Tuesday"),
	     	  "Hour": (17, "5 pm")},
	    36: {"Day": (2, "Tuesday"),
		      "Hour": (18, "5:30 pm")},
      37: {"Day": (3, "Wednesday"),
		      "Hour": (1, "8 am")},
   	  38: {"Day": (3, "Wednesday"),
		      "Hour": (2, "8:30 am")},
	    39: {"Day": (3, "Wednesday"),
	     	  "Hour": (3, "9 am")},
	    40: {"Day": (3, "Wednesday"),
		      "Hour": (4, "9:30 am")},
   	  41: {"Day": (3, "Wednesday"),
		      "Hour": (5, "10 am")},
	    42: {"Day": (3, "Wednesday"),
	     	  "Hour": (6, "10:30 am")},
      43: {"Day": (3, "Wednesday"),
	     	  "Hour": (7, "11 am")},
      44: {"Day": (3, "Wednesday"),
		      "Hour": (8, "11:30 am")},
   	  45: {"Day": (3, "Wednesday"),
		      "Hour": (9, "1 pm")},
	    46: {"Day": (3, "Wednesday"),
	     	  "Hour": (10, "1:30 pm")},
	    47: {"Day": (3, "Wednesday"),
		      "Hour": (11, "2 pm")},
   	  48: {"Day": (3, "Wednesday"),
		      "Hour": (12, "2:30 pm")},
	    49: {"Day": (3, "Wednesday"),
	     	  "Hour": (13, "3 pm")},
      50: {"Day": (3, "Wednesday"),
	     	  "Hour": (14, "3:30 pm")},
      51: {"Day": (3, "Wednesday"),
		      "Hour": (15, "4 pm")},
   	  52: {"Day": (3, "Wednesday"),
		      "Hour": (16, "4:30 pm")},
	    53: {"Day": (3, "Wednesday"),
	     	  "Hour": (17, "5 pm")},
	    54: {"Day": (3, "Wednesday"),
		      "Hour": (18, "5:30 pm")},
      55: {"Day": (4, "Thursday"),
		      "Hour": (1, "8 am")},
   	  56: {"Day": (4, "Thursday"),
		      "Hour": (2, "8:30 am")},
	    57: {"Day": (4, "Thursday"),
	     	  "Hour": (3, "9 am")},
	    58: {"Day": (4, "Thursday"),
		      "Hour": (4, "9:30 am")},
   	  59: {"Day": (4, "Thursday"),
		      "Hour": (5, "10 am")},
	    60: {"Day": (4, "Thursday"),
	     	  "Hour": (6, "10:30 am")},
      61: {"Day": (4, "Thursday"),
	     	  "Hour": (7, "11 am")},
      62: {"Day": (4, "Thursday"),
		      "Hour": (8, "11:30 am")},
   	  63: {"Day": (4, "Thursday"),
		      "Hour": (9, "1 pm")},
	    64: {"Day": (4, "Thursday"),
	     	  "Hour": (10, "1:30 pm")},
	    65: {"Day": (4, "Thursday"),
		      "Hour": (11, "2 pm")},
   	  66: {"Day": (4, "Thursday"),
		      "Hour": (412, "2:30 pm")},
	    67: {"Day": (4, "Thursday"),
	     	  "Hour": (13, "3 pm")},
      68: {"Day": (4, "Thursday"),
	     	  "Hour": (14, "3:30 pm")},
      69: {"Day": (4, "Thursday"),
		      "Hour": (15, "4 pm")},
   	  70: {"Day": (4, "Thursday"),
		      "Hour": (16, "4:30 pm")},
	    71: {"Day": (4, "Thursday"),
	     	  "Hour": (17, "5 pm")},
	    72: {"Day": (4, "Thursday"),
		      "Hour": (18, "5:30 pm")},
      73: {"Day": (5, "Friday"),
		      "Hour": (1, "8 am")},
   	  74: {"Day": (5, "Friday"),
		      "Hour": (2, "8:30 am")},
	    75: {"Day": (5, "Friday"),
	     	  "Hour": (3, "9 am")},
	    76: {"Day": (5, "Friday"),
		      "Hour": (4, "9:30 am")},
   	  77: {"Day": (5, "Friday"),
		      "Hour": (5, "10 am")},
	    78: {"Day": (5, "Friday"),
	     	  "Hour": (6, "10:30 am")},
      79: {"Day": (5, "Friday"),
	     	  "Hour": (7, "11 am")},
      80: {"Day": (5, "Friday"),
		      "Hour": (8, "11:30 am")},
   	  81: {"Day": (5, "Friday"),
		      "Hour": (9, "1 pm")},
	    82: {"Day": (5, "Friday"),
	     	  "Hour": (10, "1:30 pm")},
	    83: {"Day": (5, "Friday"),
		      "Hour": (11, "2 pm")},
   	  84: {"Day": (5, "Friday"),
		      "Hour": (12, "2:30 pm")},
	    85: {"Day": (5, "Friday"),
	     	  "Hour": (13, "3 pm")},
      86: {"Day": (5, "Friday"),
	     	  "Hour": (14, "3:30 pm")},
      87: {"Day": (5, "Friday"),
		      "Hour": (15, "4 pm")},
   	  88: {"Day": (5, "Friday"),
		      "Hour": (16, "4:30 pm")},
	    89: {"Day": (5, "Friday"),
	     	  "Hour": (17, "5 pm")},
	    90: {"Day": (5, "Friday"),
		      "Hour": (18, "5:30 pm")}}

In [12]:
TD = {1: {("Monday")},
     2: {("Tuesday")},
     3: {("Wednesday")},
     4: {("Thursday")},
     5: {("Friday")}
}

A set of Room R

In [13]:
R = {1: {"Name":'SC6409',
		 "Capacity": 40,
		 "Type": "lecture"},
	   2: {"Name":'SC6410',
		 "Capacity": 8,
		 "Type": "lecture",},
		 3: {"Name":'mirrorRoom',
		 "Capacity": 8,
		 "Type": "lecture",},
		 4: {"Name":'labRoom',
		 "Capacity": 40,
		 "Type": "lab",},
		 5: {"Name":'SC6501',
		 "Capacity": 119,
		 "Type": "lecture",},
		 6: {"Name":'SC6502',
		 "Capacity": 104,
		 "Type": "lecture",}
		      }

A set of courses C

In [27]:
C = {1: {"courseName": 'SC653205',
         "teachers": {1:'A'},
         "courseCapacity": 40,
         "hoursPerWeek": 4,
         "type": ["lecture", "lecture"]},
     2: {"courseName": 'SC653206',
         "teachers": {2:'B'},
         "courseCapacity": 80,
         "hoursPerWeek": 4,
         "type": ["lecture", "lecture"]},
     3: {"courseName": 'SC653301',
         "teachers": {2:'B'},
         "courseCapacity": 40,
         "hoursPerWeek": 3,
         "type": ["lecture", "lecture"]},
     4: {"courseName": 'SC663405',
         "teachers": {3:'C'},
         "courseCapacity": 40,
         "hoursPerWeek": 3,
         "type": ["lab", "lab"]},
     5: {"courseName": 'SC653402',
         "teachers": {1:'A', 3:'C'},
         "courseCapacity": 40,
         "hoursPerWeek": 4,
         "type": ["lab", "lab"]},
     }

A set of professor P

In [15]:
import numpy as np
P = {1: {'Name':'A',
         'course': {1:'SC653205', 5:'SC653402'},
         'weight':np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0, 0 ,0],
                   [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0, 0.5, 0.5 ,0.5],
                   [0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0.5, 0.5, 0.5, 0, 0.5 ,0.5],
                   [0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0.5, 1, 1, 0.5, 0.5 ,0.5],
                   [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5,0.5]])},
	   2: {'Name':'B',
         'course': {2:'SC653206', 3:'SC653301'},
         'weight':np.array([[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 0.5, 0.5 ,0.5],
                   [0, 0, 0, 0, 1, 1, 0, 0.5, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5 ,0.5],
                   [0, 0, 1, 0.5, 1, 0.5, 0.5, 1, 1, 1, 1, 1, 0.5, 1, 1, 1, 0.5 ,0.5],
                   [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0, 0, 1, 1 ,1],
                   [0, 0, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 0 ,0]])},
     3: {'Name':'C',
         'course': {4:'SC663405', 5:'SC653402'},
         'weight':np.array([[0.5, 0.5, 0.5, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0.5, 0, 1, 1 ,0.5],
                   [0, 0, 1, 1, 1, 1, 1, 0.5, 0.5, 1, 1, 1, 0.5, 0.5, 0.5, 0, 0 ,0],
                   [0, 0, 1, 1, 1, 0.5, 1, 1, 0.5, 0.5, 0.5, 1, 0.5, 1, 1, 0.5, 0.5 ,0.5],
                   [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5 ,0.5],
                   [0, 0, 0.5, 0.5, 0.5, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0, 0, 0 ,0]])}}

A set of students S

In [16]:
S = { 1: {'Major': 'STAT',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      2: {'Major': 'STAT',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      3: {'Major': 'STAT',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      4: {'Major': 'STAT',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      5: {'Major': 'STAT',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      6: {'Major': 'SIDS',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      7: {'Major': 'SIDS',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      8: {'Major': 'SIDS',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      9: {'Major': 'SIDS',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
          'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])},
      10: {'Major': 'SIDS',
          'Year': 3,
          'courseRegister':  {1:"SC653205", 2:"SC653206", 3:"SC653301", 4:"SC663405", 5:"SC653402"},
           'Availability': np.array([[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                                    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}
          }

In [17]:
p1 = P[1]['weight']
p2 = P[2]['weight']
p3 = P[3]['weight']

In [18]:
s1 = S[1]['Availability']
s2 = S[2]['Availability']
s3 = S[3]['Availability']
s4 = S[4]['Availability']
s5 = S[5]['Availability']
s6 = S[6]['Availability']
s7 = S[7]['Availability']
s8 = S[8]['Availability']
s9 = S[9]['Availability']
s10 = S[10]['Availability']

In [19]:
def student_availabilty(student, data):
    return data[student]['Availability']

s1 = student_availabilty(1, S)
s2 = student_availabilty(2, S)
s3 = student_availabilty(3, S)
s4 = student_availabilty(4, S)
s5 = student_availabilty(5, S)
s6 = student_availabilty(6, S)
s7 = student_availabilty(7, S)
s8 = student_availabilty(8, S)
s9 = student_availabilty(9, S)
s10 = student_availabilty(10, S)

print("Availability ของนักศึกษาคนที่ 1:")
print(s1)
print("Availability ของนักศึกษาคนที่ 2:")
print(s2)
print("Availability ของนักศึกษาคนที่ 3:")
print(s3)
print("Availability ของนักศึกษาคนที่ 4:")
print(s4)
print("Availability ของนักศึกษาคนที่ 5:")
print(s5)
print("Availability ของนักศึกษาคนที่ 6:")
print(s6)
print("Availability ของนักศึกษาคนที่ 7:")
print(s7)
print("Availability ของนักศึกษาคนที่ 8:")
print(s8)
print("Availability ของนักศึกษาคนที่ 9:")
print(s9)
print("Availability ของนักศึกษาคนที่ 10:")
print(s10)

Availability ของนักศึกษาคนที่ 1:
[[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
Availability ของนักศึกษาคนที่ 2:
[[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
Availability ของนักศึกษาคนที่ 3:
[[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
Availability ของนักศึกษาคนที่ 4:
[[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
Availability ของนักศึกษาคนที่ 5:
[[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 

In [20]:
import numpy as np

def get_teacher_weights(teacher_id, data):
    return data[teacher_id]['weight']

# ใช้ฟังก์ชันเพื่อดึง weights ของผู้สอนแต่ละคน
p1 = get_teacher_weights(1, P)
p2 = get_teacher_weights(2, P)
p3 = get_teacher_weights(3, P)

# แสดงผล weights
print("Weights ของผู้สอน A:")
print(p1)

print("\nWeights ของผู้สอน B:")
print(p2)

print("\nWeights ของผู้สอน C:")
print(p3)


Weights ของผู้สอน A:
[[0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.  0.  0. ]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.  0.5 0.5 0.5]
 [0.  0.  0.  1.  0.  1.  1.  1.  0.  1.  1.  1.  0.5 0.5 0.5 0.  0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.5 1.  1.  0.5 0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 0.5]]

Weights ของผู้สอน B:
[[0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 1.  0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  1.  1.  0.  0.5 1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 0.5]
 [0.  0.  1.  0.5 1.  0.5 0.5 1.  1.  1.  1.  1.  0.5 1.  1.  1.  0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.  0.  1.  1.  1. ]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 1.  1.  0.  0. ]]

Weights ของผู้สอน C:
[[0.5 0.5 0.5 1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  0.5 0.  1.  1.  0.5]
 [0.  0.  1.  1.  1.  1.  1.  0.5 0.5 1.  1.  1.  0.5 0.5 0.5 0.  0.  0. ]
 [0.  0.  1.  1.  1.  0.5 1.  1. 

In [ ]:
print(len(C[1]['teachers']))
print(len(C[2]['teachers']))
print(len(C[3]['teachers']))
print(len(C[4]['teachers']))
print(len(C[5]['teachers']))

1
1
1
1
2


In [21]:
import numpy as np

def calculate_teacher_demand(c):
    demands = {}

    for key in range(1, 6):
        course_name = c[key]["courseName"]
        teacher_count = len(c[key]["teachers"])
        hours_per_week = c[key]["hoursPerWeek"]
        course_type = c[key]["type"]

        print(f"\nCourse: {course_name}")
        print(f"Number of Teachers: {teacher_count}")

        if teacher_count == 1:
            teacher_id = list(c[key]["teachers"].keys())[0]
            teacher_matrix = get_teacher_weights(teacher_id, P)
            demands[course_name] = teacher_matrix
            print(f"Teacher {teacher_id}'s Weight Matrix:")
            print(teacher_matrix)
        elif teacher_count == 2:
            # Find the element-wise minimum of the two weight matrices
            teacher_ids = list(c[key]["teachers"].keys())
            weights1 = get_teacher_weights(teacher_ids[0], P)
            weights2 = get_teacher_weights(teacher_ids[1], P)

            min_weights = np.minimum(weights1, weights2)

            demands[course_name] = min_weights
            print(f"Minimum Weight Matrix:")
            print(min_weights)
        else:
            print("Unsupported number of teachers (more than 2).")

    return demands

# ใช้ฟังก์ชันเพื่อคำนวณความต้องการสอนของผู้สอน
teacher_demands = calculate_teacher_demand(C)



Course: SC653205
Number of Teachers: 1
Teacher 1's Weight Matrix:
[[0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.  0.  0. ]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.  0.5 0.5 0.5]
 [0.  0.  0.  1.  0.  1.  1.  1.  0.  1.  1.  1.  0.5 0.5 0.5 0.  0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.5 1.  1.  0.5 0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 0.5]]

Course: SC653206
Number of Teachers: 1
Teacher 2's Weight Matrix:
[[0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 1.  0.5 0.5 0.5 0.5]
 [0.  0.  0.  0.  1.  1.  0.  0.5 1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 0.5]
 [0.  0.  1.  0.5 1.  0.5 0.5 1.  1.  1.  1.  1.  0.5 1.  1.  1.  0.5 0.5]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.5 0.  0.  1.  1.  1. ]
 [0.  0.  1.  1.  1.  1.  1.  1.  1.  0.5 0.5 0.5 0.5 0.5 1.  1.  0.  0. ]]

Course: SC653301
Number of Teachers: 1
Teacher 2's Weight Matrix:
[[0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  0.5 0

In [ ]:
def separate_rooms_by_type(rooms_data, room_type):

    rooms_of_type = [room['Name'] for room in rooms_data.values() if room['Type'] == room_type]
    return rooms_of_type

# ตัวอย่างการใช้งาน
lab_rooms = separate_rooms_by_type(R, 'lab')
lecture_rooms = separate_rooms_by_type(R, 'lecture')

print("Lab Rooms:", lab_rooms)
print("Lecture Rooms:", lecture_rooms)


Lab Rooms: ['labRoom']
Lecture Rooms: ['SC6409', 'SC6410', 'mirrorRoom', 'SC6501', 'SC6502']


In [30]:
h_c = sum(course["hoursPerWeek"] for course in C.values())
print(h_c)

18


In [45]:
print(C[1]["hoursPerWeek"])
print(C[2]["hoursPerWeek"])
print(C[3]["hoursPerWeek"])
print(C[4]["hoursPerWeek"])
print(C[5]["hoursPerWeek"])

4
4
3
3
4


In [44]:
for course_id in C:
    hours_per_week = C[course_id]["hoursPerWeek"]
    print(hours_per_week)

4
4
3
3
4


In [31]:
h_c = 0  # สร้างตัวแปรเพื่อเก็บจำนวนคาบการสอนทั้งหมดของรายวิชา c

for course_id, course_info in C.items():
    h_c += course_info["hoursPerWeek"]

print("จำนวนคาบการสอนทั้งหมดในหนึ่งสัปดาห์ของรายวิชา c:", h_c)


จำนวนคาบการสอนทั้งหมดในหนึ่งสัปดาห์ของรายวิชา c: 18


In [ ]:
def u_crt_init(model, course, room, time):
    # Replace with actual keys from your data
    course_index = 1  # Replace with the logic to get the course index
    preferred_values = find_course_preferred(C, course_index)
    return preferred_values[time] if time in preferred_values else 0


# **Model**

In [ ]:
!pip install pyomo
import sys
import numpy as np
from pyomo import environ as pe
from pyomo.environ import *

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 30.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 6.1 MB/s eta 0:00:00


In [ ]:
# สร้างโมเดล
model = ConcreteModel()
# Sets
model.C = Set(initialize=C.keys())  # รายวิชา
model.R = Set(initialize=R.keys())  # ห้องเรียน
model.T = Set(initialize=T.keys())  # ช่วงเวลา
model.P = Set(initialize=P.keys())  # ผู้สอน
model.S = Set(initialize=S.keys())  # นักศึกษา
model.D = Set(initialize=TD.keys())
model.T_M = Set(initialize=range(1, 19))  # วันจันทร์
model.T_T = Set(initialize=range(19, 37))  # วันอังคาร
model.T_W = Set(initialize=range(37, 55))  # วันพุธ
model.T_Th = Set(initialize=range(55, 73))  # วันพฤหัสบดี
model.T_F = Set(initialize=range(73, 91))  # วันศุกร์
model.C_p = Set(initialize=P.keys())
model.C_s = Set(initialize=S.keys())
model.R_c = Set(initialize=C.keys())
model.T_p = Set(initialize=P.keys())
model.T_tc = Set(initialize=T.keys())

In [ ]:
# Parameters
model.u_crt = Param(model.C, model.R, model.T,initialize=u_crt_init)  # น้ำหนักความต้องการสอน
model.cap_r = Param(model.R, within=PositiveIntegers)  # ความจุของห้องเรียน
model.cap_c = Param(model.C, within=PositiveIntegers)  # ความจุของรายวิชา
model.h_c = Param(model.C, within=PositiveIntegers)  # จำนวนคาบการสอนทั้งหมดในหนึ่งสัปดาห์ของรายวิชา c
model.k_p = Param(model.P, within=PositiveIntegers)  # จำนวนชั่วโมงที่สามารถสอนได้ต่อวัน
model.k_s = Param(model.S, within=PositiveIntegers)  # จำนวนชั่วโมงที่สามารถเรียนได้ต่อวัน
model.k_c = Param(model.C, within=PositiveIntegers)  # จำนวนครั้งที่เรียนในรายวิชา c ในหนึ่งสัปดาห์
model.h_cd = Param(model.C, model.D, within=PositiveIntegers)  # ช่วงเวลาของวิชา c ที่เรียนในแต่ละวัน d

In [ ]:
# Variables
model.x_crt = Var(model.C, model.R, model.T, within=Binary)  # ตัวแปร binary ที่ระบุว่ารายวิชา c ได้รับการมอบหมายในห้อง r ในช่วงเวลา t
model.z_scrt = Var(model.S, model.C, model.R, model.T, within=Binary)  # ตัวแปร binary ที่ระบุว่านักศึกษา s เรียนในรายวิชา c ถูกมอบหมายให้เรียนห้อง r ในช่วงเวลา t
model.w_c = Var(model.C, within=Binary)  # ตัวแปร binary ที่ระบุว่ารายวิชา c ได้รับการจัดตาราง
model.w_c_d = Var(model.C, model.D, within=Binary)  # ตัวแปร binary ที่ระบุว่ารายวิชา c ถูกจัดตารางในวัน d
model.v_cd = Var(model.C, model.D, within=Binary)  # ตัวแปร binary ที่ระบุว่ารายวิชา c ที่เรียนในวัน d ∈ D

In [ ]:
model.objective = Objective(expr=sum(model.x_crt[c, r, t] for c in model.C for r in model.R_c for t in model.T), sense=maximize)

In [ ]:
# Objective Function
model.obj = Objective(
    expr=sum(model.u_crt[c, r, t] * model.x_crt[c, r, t] for c in model.C for r in model.C for t in model.T),
    sense=maximize
)

ERROR:pyomo.core:Rule failed when generating expression for Objective obj with index 0:
KeyError: "Cannot treat the scalar component 'obj' as an indexed component"
ERROR:pyomo.core:Constructing component 'obj' from data=None failed:
KeyError: "Cannot treat the scalar component 'obj' as an indexed component"


KeyError: ignored

In [ ]:
# Objective Function
model.obj = Objective(
    expr=sum((model.u_crt[c, r, t] / model.h_c[c]) * model.x_crt[c, r, t] for c in model.C for r in model.C for t in model.T),
    sense=maximize
)

ValueError: ignored

In [ ]:
# Constraints
# ข้อจำกัดที่ 1
def con1(model, t, r):
    return sum(model.x_crt[c, r, t] for c in model.C) <= 1
model.con1 = Constraint(model.T, model.R, rule=con1)


In [ ]:
# ข้อจำกัดที่ 2
def con2(model, p, t):
    return sum(model.x_crt[c, r, t] for c in model.C_p for r in model.R_c[c] if p in model.T_p[c]) <= 1
model.con2 = Constraint(model.P, model.T, rule=con2)


In [ ]:
# 3. จำนวนนักศึกษาต้องไม่มากกว่าความจุห้องเรียน
def con3(model, r, t):
    return sum(model.z_scrt[s, c, r, t] for s in model.S for c in model.C for r in model.R for t in model.T) <= model.Cap_r[r]
model.con3 = Constraint(model.R, model.T, rule=con3)

In [ ]:
# 4. จำนวนนักศึกษาต้องไม่มากกว่าความจุรายวิชา
def con4(model, c, t):
    return sum(model.z_scrt[s, c, r, t] for s in model.S for c in model.C for r in model.R for t in model.T) <= model.Cap_c[c]
model.con4 = Constraint(model.C, model.T, rule=con4)

# **solve**

In [ ]:
!sudo apt-get install glpk-utils
solver = pe.SolverFactory('glpk', executable='/usr/bin/glpsol')
solution = solver.solve(model)

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libamd2 libcolamd2 libglpk40 libsuitesparseconfig5
Suggested packages:
  libiodbc2-dev
The following NEW packages will be installed:
  glpk-utils libamd2 libcolamd2 libglpk40 libsuitesparseconfig5
0 upgraded, 5 newly installed, 0 to remove and 24 not upgraded.
Need to get 625 kB of archives.
After this operation, 2,158 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsuitesparseconfig5 amd64 1:5.10.1+dfsg-4build1 [10.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libamd2 amd64 1:5.10.1+dfsg-4build1 [21.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcolamd2 amd64 1:5.10.1+dfsg-4build1 [18.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libglpk40 amd64 5.0-1 [361 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 glpk-ut

In [ ]:
from pyomo.opt import SolverFactory

# กำหนด Solver

opt = pe.SolverFactory('glpk')
opt.solve(model, tee=True)

# แสดงผลลัพธ์
model.display()

Streaming output truncated to the last 5000 lines.
         (9, 1, 6, 20) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 21) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 22) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 23) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 24) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 25) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 26) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 27) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 28) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 29) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 30) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 31) :     0 :  None :     1 : False :  True : Binary
         (9, 1, 6, 32) :     0 :  None :     1 : False :  True : Binary
         (9, 

In [ ]:
# บันทึกโมเดลเป็นไฟล์ .lp
model.write('model.lp', io_options={'symbolic_solver_labels': True})

from google.colab import files
files.download('model.lp')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>